---
title: "Creative Assignment 4"
author: "Maggie Weese"
date: "10/1/2020"
output: html_document
---
```{r, message=FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

```{r}
BPP_libraries <- st_read(
  "https://data.baltimorecity.gov/api/geospatial/2fex-mveq?method=export&format=KML")
```

```{r}
opq(bbox = 'Baltimore MD USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/Baltimore_Streets.osm')
```

```{r}
Bmore_state_plane <- "+proj=omerc +lat_0=39.304635 +lonc=-76.614429 +alpha=0 +k=1 +x_0=106.4881889763779 +y_0=788.8544577089153 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"

bmore_street_features <- opq(bbox = 'Baltimore MD USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

bmore_streets <- bmore_street_features$osm_lines %>%
  st_transform(crs = Bmore_state_plane)
```

```{r, fig.height=8, fig.width=8}
ggplot(bmore_streets) +
  geom_sf() +
  theme_map()
```

```{r}
path_otp <- otp_dl_jar("OTP")

```

```{r, message=FALSE, results='hide'}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```

```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
```

```{r}
# Connect to opentripplanner
otpcon <- otp_connect()
```

```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = BPP_libraries, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = Bmore_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = BPP_libraries, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = Bmore_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)

otp_stop()
```

```{r, fig.height=8, fig.width=8}

#Question: In the 3 modes graph, all of the points appear with a by car isochrone but not in this graph

right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = BPP_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 10 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")


```

```{r}
#Not sure what is up with my scale - the numbers seem too big, also why did it remove 8 rows?

iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a public pool\n(square km)",
            breaks = breaks <- seq(0, 2000000, by = 200000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a public pool\n(square km)",           
            breaks = breaks <- seq(0, 15000000, by = 1500000),
            labels = breaks / 1000000) + 
  theme_bw()

```

```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = BPP_libraries, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = Bmore_state_plane) %>%
  mutate(mode = "walk")

iso_5min_bike <- 
  otp_isochrone(otpcon = otpcon, fromPlace = BPP_libraries, 
                mode = "BICYCLE", cutoffSec = 300) %>%
  st_transform(crs = Bmore_state_plane) %>%
  mutate(mode = "bike")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = BPP_libraries, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = Bmore_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes2 <- rbind(iso_5min_walk, iso_5min_drive, iso_5min_bike)

otp_stop()
```

```{r, fig.height=8, fig.width=8}
right_side <- st_bbox(iso_all_modes2)$xmax
left_side  <- st_bbox(iso_all_modes2)$xmin
top_side <- st_bbox(iso_all_modes2)$ymax
bottom_side <- st_bbox(iso_all_modes2)$ymin

ggplot(iso_all_modes2) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = BPP_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800", "#FC4E07"),
                      name = "Area that is reachable within 10 minutes",
                      labels = c("By foot","By car", "By bike")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")

```

```{r}
#similar issue with scale as above

iso_areas2 <- iso_all_modes2 %>%
  mutate(area = st_area(iso_all_modes2)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(bike), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a public pool\n(square km)",
            breaks = breaks <- seq(100000, 20000000, by = 200000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a public pool\n(square km)",           
            breaks = breaks <- seq(100000, 20000000, by = 200000),
            labels = breaks / 1000000) + 
  theme_bw()
```

```{r}
#dot_schools <- schools[dortchester,]   
#[1:10,] - with comma, first 10 rows, without would be column
#opt_plan() - will find routes between two points

```

