---
title: "SAGE Map"
author: "Maggie Weese"
date: "10/23/2020"
output: 
  html_document:
    theme: spacelab
    toc: true
    toc_float: true
 
---

## Downloading Libraries
```{r, warning=FALSE, results=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(stringr)
```

## Creating Centroids for My Data
```{r, warning=FALSE, results=FALSE, message=FALSE}

SAGE_pts <- Subgrant_Info_Tracker_forMap_Update



```

```{r}
SAGE_map <- leaflet(SAGE_pts) %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite (default)") %>%
  addProviderTiles(providers$Esri.WorldStreetMap, group = "Esri Street Map") %>%
  
  
 addMarkers(~longitude, ~latitude)





SAGE_map
```

```{r}

R1 <- SAGE_pts[1:5,]

R2 <- SAGE_pts[6:8,]

R3 <- SAGE_pts[9:15,]

R4 <- SAGE_pts[16:19,]

R5 <- SAGE_pts[20:24,]

WEJ <- SAGE_pts[25:35,]

Worker <- SAGE_pts[36:41,]


num <- as.numeric(c(6000, 400, 10, 5000, 10))


SAGE_pts$describe <- paste("<b>",  
         "<p style='color:Black;'>", SAGE_pts$ProjectName, "</b>", "<br/>", 
        "<b>", "<p style='color:Black;'>", "Project Lead:", "</b>", SAGE_pts$Lead, "<br/>", 
        "<b>", "<p style='color:Black;'>", "Project Partners:", "</b>", SAGE_pts$Partners, "<br/>",
        "<b>", "<p style='color:Black;'>", "Location:","</b>", SAGE_pts$Locations) %>%
  lapply(htmltools::HTML)

```

```{r, fig.width=8, fig.height=8}

SAGE_map1 <- leaflet(SAGE_pts) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik) %>%
  

addCircles(data=R1, ~longitude, ~latitude, fillColor="Green", fillOpacity = 1, color="Green", group = "Investment Mapping Tools", highlightOptions = highlightOptions(color = "Black", opacity = .2), 
                                    popup = ~describe) %>%
               

 addCircles(data=R2, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "Yellow", color="Yellow",  radius = 800, group = "Remedy and OGMs", highlightOptions = highlightOptions(color = "Black", opacity = .2), 
                                    popup = ~describe) %>%
 
 
 addCircles(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "Orange", color="Orange", radius = 800, group = "Community Driven Strategies", highlightOptions = highlightOptions(color = "Black", opacity = 0.2),
                           popup = ~describe) %>%

 
  addCircles(data=R4, ~longitude, ~latitude, fillColor="Red", color="Red", radius = 800, group = "Enforcement Strategies", highlightOptions = highlightOptions(color = "Black", opacity = 0.2),
                                  popup = ~describe) %>%

  
    addCircles(data=R5, ~longitude, ~latitude, fillOpacity=0.8, fillColor="Blue", color="Blue",  radius = 800, group = "Remedy for Mining Disasters", highlightOptions = highlightOptions(color = "Black", opacity = 0.2),
                                   popup = ~describe) %>%


addCircles(data=WEJ, ~longitude, ~latitude, fillOpacity=0.8, fillColor="Purple", color="Purple", radius = 80, group = "Women's Economic Justice", highlightOptions = highlightOptions(color = "Black", opacity = 0.2),
                                      popup = ~describe) %>%

  
addCircles(data=Worker, ~longitude, ~latitude, fillOpacity=0.8, fillColor="Pink", color="Pink", opacity = .5, radius = 80, group = "Round 6", highlightOptions = highlightOptions(color = "Black", opacity = 0.2),
                                    popup = ~describe) %>%

addLayersControl(
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Round 6"),
    options = layersControlOptions(collapsed = FALSE))




SAGE_map1


```

```{r, fig.width=8, fig.height=8}

SAGE_map2 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$OpenStreetMap.DE) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#618f5b", fillOpacity = .95, color=NA, group = "Investment Mapping Tools", radius = 5.2,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.9, fillColor = "#bcbb24", color=NA, group = "Remedy and OGMs", radius = 5.2,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.7, fillColor = "#ca7112", color= NA, group = "Community Driven Strategies", radius = 5.2,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.75, fillColor="#b13128", color= NA, group = "Enforcement Strategies", radius = 5.2,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.8, fillColor="#516c86", color= NA, group = "Remedy for Mining Disasters", radius = 5.2,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor="#774a6a", fillOpacity = 0., group = "Women's Economic Justice", radius = 5.2,
                                      popup = ~describe) %>%

addControl("Project Locations", position = "topright") %>%


addLayersControl(
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Round 6"),
    options = layersControlOptions(collapsed = FALSE)) %>%


  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_map2
```

```{r, fig.width=8, fig.height=8}

SAGE_map5 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#C9C236", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#A6608D", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6D6D6E", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%


addLegend(position = "topright", 
            colors = c("#4F8F33", 
                       "#DEDE2A",
                      "#D97823",
                      "#A62626",
                      "#08385C",
                      "#7D2A8F",
                       "#818182"
                      ),
           
           
            labels = c("Investment Mapping Tools",
                       "Remedy and OGMs",
                       "Community Driven Strategies",
                       "Enforcement Strategies",
                       "Remedy for Mining Disasters",
                       "Women's Economic Justice",
                      "Worker Empowerment Strategies"
                       ),
           
           
            title = "SAGE Fund Project Locations")  %>%
  
  addLayersControl(position = "topleft",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>%

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_map5
```


```{r}

SAGE_map4 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerLabelsUnder) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#C9C236", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#A6608D", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%


addLegend(position = "topright", 
            colors = c("#4F8F33", 
                       "#DEDE2A",
                      "#D97823",
                      "#A62626",
                      "#08385C",
                      "#7D2A8F",
                       "#6C6C6F"
                      ),
           
           
            labels = c("Investment Mapping Tools",
                       "Remedy and OGMs",
                       "Community Driven Strategies",
                       "Enforcement Strategies",
                       "Remedy for Mining Disasters",
                       "Women's Economic Justice",
                      "Worker Empowerment Strategies"
                       ),
           
           
            title = "SAGE Fund Project Locations")  %>%
  
  addLayersControl(position = "topleft",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>%

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_map4
```


```{r}
saveWidget(SAGE_map4, file = "SAGE_Map4.html")

```

#Final Map

```{r}
SAGE_map3 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.84, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%


addLegend(position = "topright", 
            colors = c("#67A62B", 
                       "#D9CE04",
                      "#D97825",
                      "#BC302F",
                      "#3385A2",
                      "#8F537A",
                       "#6C6C6F"
                      ),
          
          opacity=.78,
           
           
            labels = c("Investment Mapping Tools",
                       "Remedy and OGMs",
                       "Community Driven Strategies",
                       "Enforcement Strategies",
                       "Remedy for Mining Disasters",
                       "Women's Economic Justice",
                      "Worker Empowerment Strategies"
                       ),
           
           
            title = "SAGE Fund Projects")  %>%   
  

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_map3
```
```{r}
saveWidget(SAGE_map3, file = "SAGE_Map3.html")

```

#Map for Each Round

##Round 1
```{r}

SAGE_mapR1 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Remedy and OGMs") %>%  hideGroup("Community Driven Strategies") %>%  hideGroup("Enforcement Strategies") %>% hideGroup("Remedy for Mining Disasters") %>% hideGroup("Women's Economic Justice") %>% hideGroup("Worker Empowerment Strategies") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapR1
           
  
```

```{r}
saveWidget(SAGE_mapR1, file = "SAGE_MapR1.html")
```


##Round 2
```{r}

SAGE_mapR2 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Investment Mapping Tools") %>%  hideGroup("Community Driven Strategies") %>%  hideGroup("Enforcement Strategies") %>% hideGroup("Remedy for Mining Disasters") %>% hideGroup("Women's Economic Justice") %>% hideGroup("Worker Empowerment Strategies") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapR2
```
 
```{r}
saveWidget(SAGE_mapR2, file = "SAGE_MapR2.html")
```          

##Round 3
```{r}

SAGE_mapR3 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Investment Mapping Tools") %>%  hideGroup("Remedy and OGMs") %>%  hideGroup("Enforcement Strategies") %>% hideGroup("Remedy for Mining Disasters") %>% hideGroup("Women's Economic Justice") %>% hideGroup("Worker Empowerment Strategies") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapR3
```

```{r}
saveWidget(SAGE_mapR3, file = "SAGE_MapR3.html")
```     


##Round 4
```{r}

SAGE_mapR4 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Investment Mapping Tools") %>%  hideGroup("Remedy and OGMs") %>%  hideGroup("Community Driven Strategies") %>% hideGroup("Remedy for Mining Disasters") %>% hideGroup("Women's Economic Justice") %>% hideGroup("Worker Empowerment Strategies") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapR4
```

```{r}
saveWidget(SAGE_mapR4, file = "SAGE_MapR4.html")
```  

##Round 5
```{r}

SAGE_mapR5 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Investment Mapping Tools") %>%  hideGroup("Remedy and OGMs") %>%  hideGroup("Community Driven Strategies") %>% hideGroup("Enforcement Strategies") %>% hideGroup("Women's Economic Justice") %>% hideGroup("Worker Empowerment Strategies") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapR5
```

```{r}
saveWidget(SAGE_mapR5, file = "SAGE_MapR5.html")
```  


##Round WEJ
```{r}

SAGE_mapWEJ <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Investment Mapping Tools") %>%  hideGroup("Remedy and OGMs") %>%  hideGroup("Community Driven Strategies") %>% hideGroup("Enforcement Strategies") %>% hideGroup("Remedy for Mining Disasters") %>% hideGroup("Worker Empowerment Strategies") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapWEJ
```

```{r}
saveWidget(SAGE_mapWEJ, file = "SAGE_MapWEJ.html")
```  

##Round 6
```{r}

SAGE_mapR6 <- leaflet(SAGE_pts, options = leafletOptions(minZoom = 2, maxZoom = 4)) %>%
  addProviderTiles(providers$CartoDB.VoyagerNoLabels) %>%
  

addCircleMarkers(data=R1, ~longitude, ~latitude, fillColor="#67A62B", fillOpacity = .85, color=NA, group = "Investment Mapping Tools", radius = 7,
                           popup = ~describe) %>%

               

addCircleMarkers(data=R2, ~longitude, ~latitude, fillOpacity=.92, fillColor = "#D9CE04", color=NA, group = "Remedy and OGMs", radius = 7,
                           popup = ~describe) %>% 
  
 
addCircleMarkers(data=R3, ~longitude, ~latitude, fillOpacity=0.8, fillColor = "#D97925", color= NA, group = "Community Driven Strategies", radius = 7,
                           popup = ~describe) %>%

 
addCircleMarkers(data=R4, ~longitude, ~latitude, fillOpacity=0.85, fillColor="#BC302F", color= NA, group = "Enforcement Strategies", radius = 7,
                                  popup = ~describe) %>%

  
addCircleMarkers(data=R5, ~longitude, ~latitude, fillOpacity=0.9, fillColor="#3385A6", color= NA, group = "Remedy for Mining Disasters", radius = 7,
                                   popup = ~describe) %>%


addCircleMarkers(data=WEJ, ~longitude, ~latitude, color = NA, fillColor= "#8F537A", fillOpacity = 0.82, group = "Women's Economic Justice", radius = 7,
                                      popup = ~describe) %>%

addCircleMarkers(data=Worker, ~longitude, ~latitude, color = NA, fillColor= "#6C6C6F", fillOpacity = 0.8, group = "Worker Empowerment Strategies", radius = 7,
                                      popup = ~describe) %>%

   addControl("SAGE Fund Projects", position = "topright") %>%
  
     addLayersControl(position = "topright",
    overlayGroups = c("Investment Mapping Tools", "Remedy and OGMs", "Community Driven Strategies", "Enforcement Strategies", "Remedy for Mining Disasters", "Women's Economic Justice", "Worker Empowerment Strategies"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  
  hideGroup("Investment Mapping Tools") %>%  hideGroup("Remedy and OGMs") %>%  hideGroup("Community Driven Strategies") %>% hideGroup("Enforcement Strategies") %>% hideGroup("Remedy for Mining Disasters") %>% hideGroup("Women's Economic Justice") %>% 

  setMaxBounds( lng1 = -150,
                lat1 = -100,
                lng2 = 150,
                lat2 = 100)


SAGE_mapR6
```

```{r}
saveWidget(SAGE_mapR6, file = "SAGE_MapR6.html")
```  